### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by paulhayes** [josephdadams/USBRelay#4]
Can you publish this latest version on npm, I'm still getting the old one from here https://www.npmjs.com/package/@josephdadams/usbrelay

All the best

**Comment by paulhayes** [comment]
Hi @josephdadams, any chance of you following this up soon?

**Comment by josephdadams** [comment]
@paulhayes I added you on npm as a maintainer, can you go there and publish?

**Comment by paulhayes** [comment]
Thanks @josephdadams, I will

**Comment by paulhayes** [comment]
Hi @josephdadams, can you add me as a contributor to the repository too. As I need to make a small change to the package.json before publishing.

**Comment by paulhayes** [comment]
Thanks for adding me as an collaborator on github @josephdadams. I was able to push the change.

Weirdly, it looks like I never got the invite to be a maintainer on the npm package:
https://www.npmjs.com/package/@josephdadams/usbrelay

This is my user: https://www.npmjs.com/settings/paulhayes/profile

Is it possible you invited another user by accident? My name is quite common.

**Comment by josephdadams** [comment]
You're added to the npm package now. I guess it didn't go through before!
