### ISSUE TITLE
[Error] TypeError: Cannot read property 'indexOf' of undefined [Tally Arbiter Relay Listener] 

### ISSUE THREAD

**Issue by blakecarrasco** [josephdadams/USBRelay#5]
Hi,

Recently I have been trying to setup a usb relay system using Tally Arbiter(TA) and the TA Relay Listener on Windows 10.

When launching the TA Relay Listener I encounter the following error

`index.js:39 TypeError: Cannot read property 'indexOf' of undefined `

and thus it it does establish connection with the USB relay device I have connected.

The reason I am posting this here is because I traced back the error to this dependency, have come up with a fix for the error that allowed me to get my system up and running.  I just wanted to make sure the fix seems valid with the maintainers of this dependency.

Inside of index.js for USBrelay...inside the constructor for 'devicePath'..it states this

`*[LINE: 38]* return device.product.indexOf("USBRelay") !== -1;`

to fix the error I simply matched the return statement to match the same return from line 18

`*[LINE 18:]* return device.product && device.product.indexOf("USBRelay") !== -1;`

so now line 38 reads...

`*[LINE 38]* return device.product && device.product.indexOf("USBRelay") !== -1;`

It seems to me that for some reason the omission of `device.product &&` from the return statement makes the latter condition break since it doesn't have proper reference.

Once these two lines match the software works flawlessly.

Hopefully this makes sense, and if it's actually an issue for people on other systems, pushing this fix to the repo could be beneficial.

Thanks for reading.

**Comment by josephdadams** [comment]
Sure, just submit a PR for this

**Comment by josephdadams** [comment]
Fixed in #6
