### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by paulhayes** [josephdadams/USBRelay#8]
Hi Joseph, I've update the node-hid dependancy to use the latest version. I've tested and it works. I did this to resolve the following issue, in my node red package.

https://github.com/paulhayes/node-red-contrib-usb-hid-relay/issues/7

Could you publish the latest version to npm.

**Comment by josephdadams** [comment]
Done, I added a github action to help do this in the future, just update `package.json` and it will auto publish the new version to npm.

**Comment by paulhayes** [comment]
What a great idea, I'll have to set this up on my own npm packages.

Thanks Joseph
