### ISSUE TITLE
Works with ch340 chip?

### ISSUE THREAD

**Issue by AlexVFornazieri** [josephdadams/USBRelay#9]
Hey guys,

I have no ideia how the control by USB works, I found this module in Aliexpress: https://a.aliexpress.com/_mtfDLbc This code works with this board? If not, have some instructions for find compatible modules or adapt the code to works witch it too? Any reads recommendation for help-me in this subject is welcome too

**Comment by paulhayes** [comment]
Hi there. No this repo isn't for ch340. However it's actually much easier to control the ch340 using standard serial io ( com ports in Windows ).

I have some code for these style. It's normally just sending 2bytes. I'll dig out an example.
